# Generated by Django 5.0 on 2026-03-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('cover_path', models.CharField(blank=True, max_length=255)),
                ('is_pinned', models.BooleanField(db_index=True, default=False)),
                ('order', models.IntegerField(default=0)),
                ('articles', models.ManyToManyField(blank=True, related_name='collections', to='articles.article')),
            ],
            options={
                'ordering': ['-is_pinned', 'order', '-updated_at', '-id'],
                'indexes': [models.Index(fields=['is_pinned', 'order'], name='idx_collection_pin'), models.Index(fields=['slug'], name='idx_collection_slug')],
            },
        ),
    ]
