# Generated by Django 4.2.29 on 2026-03-04 14:58

import math
import re

from django.db import migrations, models

CJK_CHAR_PATTERN = re.compile(r"[\u4e00-\u9fff]")
WORD_PATTERN = re.compile(r"[A-Za-z0-9_]+")
FENCED_CODE_BLOCK_PATTERN = re.compile(r"(```[\s\S]*?```|~~~[\s\S]*?~~~)")


def _estimate_read_minutes(markdown_content: str) -> int:
    content = markdown_content or ""
    without_code = FENCED_CODE_BLOCK_PATTERN.sub(" ", content)
    cjk_chars = len(CJK_CHAR_PATTERN.findall(without_code))
    words = len(WORD_PATTERN.findall(without_code))
    total_units = cjk_chars + words
    if total_units <= 0:
        return 1
    return max(1, math.ceil(total_units / 300))


def backfill_article_read_minutes(apps, schema_editor) -> None:
    Article = apps.get_model("articles", "Article")
    for article in Article.objects.only("id", "markdown_content").iterator(chunk_size=200):
        read_minutes = _estimate_read_minutes(article.markdown_content)
        Article.objects.filter(id=article.id).update(read_minutes=read_minutes)


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0002_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="read_minutes",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RunPython(backfill_article_read_minutes, migrations.RunPython.noop),
    ]
