# Generated by Django 4.2.29 on 2026-03-05 10:10

import math
import re

from django.db import migrations

CJK_CHAR_PATTERN = re.compile(r"[\u4e00-\u9fff]")
WORD_PATTERN = re.compile(r"[A-Za-z0-9_]+")
FENCED_CODE_BLOCK_PATTERN = re.compile(r"(```[\s\S]*?```|~~~[\s\S]*?~~~)")
MARKDOWN_IMAGE_PATTERN = re.compile(r"!\[[^\]]*]\([^)\n]+\)")
HTML_IMG_TAG_PATTERN = re.compile(r"<img\b[^>]*>", re.IGNORECASE)


def _estimate_read_minutes(markdown_content: str) -> int:
    content = markdown_content or ""
    without_code = FENCED_CODE_BLOCK_PATTERN.sub(" ", content)
    markdown_images = MARKDOWN_IMAGE_PATTERN.findall(without_code)
    html_images = HTML_IMG_TAG_PATTERN.findall(without_code)
    image_count = len(markdown_images) + len(html_images)

    text_only_content = MARKDOWN_IMAGE_PATTERN.sub(" ", without_code)
    text_only_content = HTML_IMG_TAG_PATTERN.sub(" ", text_only_content)
    cjk_chars = len(CJK_CHAR_PATTERN.findall(text_only_content))
    words = len(WORD_PATTERN.findall(text_only_content))
    total_units = cjk_chars + words

    text_minutes = total_units / 300 if total_units > 0 else 0
    image_minutes = image_count * 10 / 60
    return max(1, math.ceil(text_minutes + image_minutes))


def backfill_article_read_minutes(apps, schema_editor) -> None:
    Article = apps.get_model("articles", "Article")
    for article in Article.objects.only("id", "markdown_content").iterator(chunk_size=200):
        read_minutes = _estimate_read_minutes(article.markdown_content)
        Article.objects.filter(id=article.id).update(read_minutes=read_minutes)


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_article_read_minutes"),
    ]

    operations = [
        migrations.RunPython(backfill_article_read_minutes, migrations.RunPython.noop),
    ]

